export const types = {
  SIGNIN: '[USERS] SIGNIN',
  SIGNUP: '[USERS] SIGNUP',
  LOGOUT: '[LOGOUT] LOGOUT',

  PUBLISH_JOB: '[JOB] PUBLISH JOB',
  ACCEPT_JOB: '[JOB] ACCEPT JOB',
  DELETE_JOB: '[JOB] DELETE JOB',
  ADD_OFFER: '[JOB] ADD OFFER',
  LOAD_JOBS: '[JOB] LOAD JOBS',
  LOAD_EMPLOYEER_JOBS: '[JOB] LOAD EMPLOYEER JOBS',
  LOAD_EMPLOYEE_JOBS: '[JOB] LOAD EMPLOYEE JOBS',
  CLEAN: '[JOB] CLEAN',
}
