export const types = {
  SIGNIN: "[USERS] SIGNIN",
  SIGNUP: "[USERS] SIGNUP",
  LOGOUT: "[LOGOUT] LOGOUT",

  SAVE_JOB: "[JOB] SAVE JOB",
  GET_ALL_JOBS: "[JOB] GET ALL JOBS",
  GET_JOB_BY_ID: "[JOB] GET JOB BY ID",
  GET_JOBS_BY_EMPLOYEER_ID: "[JOB] GET JOBS BY EMPLOYEER ID",
  GET_JOBS_BY_EMPLOYEE_ID: "[JOB] GET JOBS BY EMPLOYEE ID",
  DELETE_JOB: "[JOB] DELETE JOB",
};
